version: 2
jobs:
  build:
    
    working_directory: ~/ukrainiantolatin

    docker:
      - image: cimg/openjdk:19.0.2

    steps:

      - checkout

      - run: mvn dependency:go-offline
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
